### ISSUE TITLE
Sentinel-3 data on Google Earth Engine?

### ISSUE THREAD

**Issue by edwinytgoh** [iod-ine/igarss2022_kamchatka_hab#1]
Hello Ivan, 

Thank you for the fascinating talk and for the open source code! After attending the IGARSS plenary session and learning about Google Earth Engine, I was wondering if Google EE would be a viable option to automate the acquisition of Sentinel-3 chlorophyll data? This was the first link from my quick search: https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S3_OLCI

**Comment by iod-ine** [comment]
Hi @edwinytgoh,

Thank you for the compliment and the question! I am an active user of Google Earth Engine, especially when prototyping and exploring. However, as far as I know, GEE only provides access to land observations of Sentinel-3 because it mirrors the Copernicus Open Access Hub. Water observations, which contain the required chlorophyll concentrations, are provided by EUMETSAT and are not accessible in GEE (at leas currently).
